---
services:
  perceived-temp-service:
    container_name: svc-motion-alarm
    image: svenschmidt1502/svc-motion-alarm:latest
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
      - 'KAFKA_MOTION_TOPIC=${KAFKA_MOTION_TOPIC}'
      - 'DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}'
    deploy:
      replicas: 1